package com.creditos.creditoscomerciales;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class autonomiasduales implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "banca")
	private java.lang.String banca;
	@org.kie.api.definition.type.Label(value = "credito")
	private java.lang.String credito;
	@org.kie.api.definition.type.Label(value = "grupo")
	private java.lang.String grupo;

	public autonomiasduales() {
	}

	public java.lang.String getBanca() {
		return this.banca;
	}

	public void setBanca(java.lang.String banca) {
		this.banca = banca;
	}

	public java.lang.String getCredito() {
		return this.credito;
	}

	public void setCredito(java.lang.String credito) {
		this.credito = credito;
	}

	public java.lang.String getGrupo() {
		return this.grupo;
	}

	public void setGrupo(java.lang.String grupo) {
		this.grupo = grupo;
	}

	public autonomiasduales(java.lang.String banca, java.lang.String credito,
			java.lang.String grupo) {
		this.banca = banca;
		this.credito = credito;
		this.grupo = grupo;
	}

}