package com.creditos.creditoscomerciales;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class autonomia implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "cargo")
	private java.lang.String cargo;
	@org.kie.api.definition.type.Label(value = "grupoa")
	private java.lang.String grupoa;

	public autonomia() {
	}

	public java.lang.String getCargo() {
		return this.cargo;
	}

	public void setCargo(java.lang.String cargo) {
		this.cargo = cargo;
	}

	public java.lang.String getGrupoa() {
		return this.grupoa;
	}

	public void setGrupoa(java.lang.String grupoa) {
		this.grupoa = grupoa;
	}

	public autonomia(java.lang.String cargo, java.lang.String grupoa) {
		this.cargo = cargo;
		this.grupoa = grupoa;
	}

}