package com.creditos.creditoscomerciales;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class etaparesultado implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "resulestapa")
	private java.lang.String resulestapa;

	public etaparesultado() {
	}

	public java.lang.String getResulestapa() {
		return this.resulestapa;
	}

	public void setResulestapa(java.lang.String resulestapa) {
		this.resulestapa = resulestapa;
	}

	public etaparesultado(java.lang.String resulestapa) {
		this.resulestapa = resulestapa;
	}

}