package com.creditos.creditoscomerciales;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class puesto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("cargo")
	private java.lang.String cargo;
	@org.kie.api.definition.type.Label("monto")
	private java.lang.Integer monto;

	@org.kie.api.definition.type.Label(value = "grupoa")
	private java.lang.String grupoa;

	public puesto() {
	}

	public java.lang.String getCargo() {
		return this.cargo;
	}

	public void setCargo(java.lang.String cargo) {
		this.cargo = cargo;
	}

	public java.lang.Integer getMonto() {
		return this.monto;
	}

	public void setMonto(java.lang.Integer monto) {
		this.monto = monto;
	}

	public java.lang.String getGrupoa() {
		return this.grupoa;
	}

	public void setGrupoa(java.lang.String grupoa) {
		this.grupoa = grupoa;
	}

	public puesto(java.lang.String cargo, java.lang.Integer monto,
			java.lang.String grupoa) {
		this.cargo = cargo;
		this.monto = monto;
		this.grupoa = grupoa;
	}

}