package com.creditos.creditoscomerciales;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RecuentosDiasDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "DiasTotales")
	private java.lang.String diasTotales;
	@org.kie.api.definition.type.Label(value = "DiasAdvertencia")
	private java.lang.String diasAdvertencia;

	public RecuentosDiasDTO() {
	}

	public java.lang.String getDiasTotales() {
		return this.diasTotales;
	}

	public void setDiasTotales(java.lang.String diasTotales) {
		this.diasTotales = diasTotales;
	}

	public java.lang.String getDiasAdvertencia() {
		return this.diasAdvertencia;
	}

	public void setDiasAdvertencia(java.lang.String diasAdvertencia) {
		this.diasAdvertencia = diasAdvertencia;
	}

	public RecuentosDiasDTO(java.lang.String diasTotales,
			java.lang.String diasAdvertencia) {
		this.diasTotales = diasTotales;
		this.diasAdvertencia = diasAdvertencia;
	}

}