package com.creditos.creditoscomerciales;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SLAanalista implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "autonomiacredito")
	private java.lang.String autonomiacredito;
	@org.kie.api.definition.type.Label(value = "diastotal")
	private java.lang.Integer diastotal;
	@org.kie.api.definition.type.Label(value = "color")
	private java.lang.String color;

	public SLAanalista() {
	}

	public java.lang.String getAutonomiacredito() {
		return this.autonomiacredito;
	}

	public void setAutonomiacredito(java.lang.String autonomiacredito) {
		this.autonomiacredito = autonomiacredito;
	}

	public java.lang.Integer getDiastotal() {
		return this.diastotal;
	}

	public void setDiastotal(java.lang.Integer diastotal) {
		this.diastotal = diastotal;
	}

	public java.lang.String getColor() {
		return this.color;
	}

	public void setColor(java.lang.String color) {
		this.color = color;
	}

	public SLAanalista(java.lang.String autonomiacredito,
			java.lang.Integer diastotal, java.lang.String color) {
		this.autonomiacredito = autonomiacredito;
		this.diastotal = diastotal;
		this.color = color;
	}

}