package com.creditos.creditoscomerciales.dto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Solicitud implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "email")
	private java.lang.String EMAIL;

	public Solicitud() {
	}

	public java.lang.String getEMAIL() {
		return this.EMAIL;
	}

	public void setEMAIL(java.lang.String EMAIL) {
		this.EMAIL = EMAIL;
	}

	public Solicitud(java.lang.String EMAIL) {
		this.EMAIL = EMAIL;
	}

}